### ISSUE TITLE
Bold font on variables.

### ISSUE THREAD

**Issue by itschip** [themsammy/rider-theme#3]
Hi, just a suggestion for you. In the Jetbrains IDEA theme, we almost only see bold fonts like on the screenshot for `// TODO: something` and such.

Would be nice to use the practice in this theme. Love what you have done so far.

![SetVehRadioStation](https://user-images.githubusercontent.com/59088889/138766568-e384cac4-4c78-4de8-af0b-2b6503a39152.png)

**Comment by muhammadsammy** [comment]
I think you are right, The theme looks horrible in TS, JS :+1: 
I've merged your PR (#4) Thanks you!
